#postgresql configuration
spring.datasource.url =jdbc:postgresql://dpg-d5n527kmrvns73fht79g-a.singapore-postgres.render.com/moneymanager_wdp4
spring.datasource.username =moneymanager_wdp4_user
spring.datasource.password =3T0j0KChv2405CVeXROtC0Y1o58vdDH9
